name: Agendar Evento
description: Agendamento de Evento
title: "[Evento]: "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Vamos agendar seu evento?!
  - type: input
    id: nomeevento
    attributes:
      label: Evento
      description: Qual o nome do evento?
      placeholder: ex. TDC 2023
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Site
      description: Qual o site do evento?
      placeholder: ex. https://www.tdc.com.br/
    validations:
      required: true
  - type: dropdown
    id: tipo
    attributes:
      label: Tipo
      description: O Evento será Presencial ou Online?
      options:
        - Presencial
        - Online
        - Hibrido
    validations:
      required: true
  - type: input
    id: local
    attributes:
      label: local
      description: Qual o Cidade e Estado do evento? (caso seja online, digite Online)
      placeholder: ex. São Paulo - SP / Online
    validations:
      required: true         
  - type: dropdown
    id: mes
    attributes:
      label: Mês
      description: Qual o mês do evento?
      options:
        - JANEIRO
        - FEVEREIRO
        - MARÇO
        - ABRIL
        - MAIO
        - JUNHO
        - JULHO
        - AGOSTO
        - SETEMBRO
        - OUTUBRO
        - NOVEMBRO
        - DEZEMBRO
    validations:
      required: true
  - type: input
    id: dia
    attributes:
      label: Dia
      description: Qual o dia do evento?
      placeholder: ex. 01
    validations:
      required: true      