name: Agendamento de Evento

on:
  issues:
    types: [opened]

jobs:
  agendar-evento:
    runs-on: ubuntu-latest
    env:
      ISSUE_BODY: "${{ github.event.issue.body }}"
    if: contains(github.event.issue.title, '[Evento]:')    
    steps:
      - name: Agendar Evento
        uses: actions/checkout@v3

      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.1.1
        with:
          body: ${{ env.ISSUE_BODY }}
      
      - run: |
          evento=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .evento.text | sed 's/"//g')
          site=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .site.text | sed 's/"//g')
          tipo=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .tipo.text | sed 's/"//g')
          local=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .local.text | sed 's/"//g')
          mes=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .mes.text | sed 's/"//g')
          dia=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .dia.text | sed 's/"//g')
           echo "$mes - $dia - $evento - $site - $tipo - $local"